/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

dependencies {
    // UI
    implementation(project(":utilities"))

    // Hibernate / JPA and SQLite
    implementation("org.hibernate.orm:hibernate-core:6.6.1.Final")
    implementation("org.xerial:sqlite-jdbc:3.46.0.0")
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
    implementation("org.hibernate.orm:hibernate-community-dialects:6.6.1.Final")

    // QR Code
    implementation("com.google.zxing:core:3.5.3")
    implementation("com.google.zxing:javase:3.5.3")

    // Webcam access (removed)

    // Scheduling
    implementation("org.quartz-scheduler:quartz:2.3.2")

    // Password hashing
    implementation("at.favre.lib:bcrypt:0.10.2")

    // Logging for Hibernate
    implementation("org.slf4j:slf4j-simple:2.0.16")

    // Icons for JavaFX UI
    implementation("org.kordamp.ikonli:ikonli-javafx:12.3.1")
    implementation("org.kordamp.ikonli:ikonli-fontawesome5-pack:12.3.1")
}

application {
    // Define the main class for the application.
    mainClass = "com.gymapp.app.MainApp"
    applicationDefaultJvmArgs = listOf("-Dfile.encoding=UTF-8")
}

javafx {
    version = "21"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.swing")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
